# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='filemodel',
            name='pdf_path',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebSite.User'),
            preserve_default=False,
        ),
    ]
