# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0002_auto_20190412_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
