# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('resolve', models.CharField(max_length=255)),
                ('is_test', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
    ]
